const data = {
	products: [
		{
			_id: '1',
			name: 'Slim Shirt',
			category: 'Shirts',
			image: '/images/d1.jpg',
			price: 6000,
			brand: ' Nike',
			rating: 4.85,
			numReviews: 10,
			countInStock: 12,
			description: 'high quality shirt',
		},
		{
			_id: '2',
			name: 'Fit Shirt',
			category: 'Shirts',
			image: '/images/d2.jpg',
			price: 7500,
			brand: ' Nike',
			rating: 4.25,
			numReviews: 5,
			countInStock: 0,
			description: 'high quality shirt',
		},
		{
			_id: '3',
			name: 'Best Pants',
			category: 'Pants',
			image: '/images/p1.jpg',
			price: 7000,
			brand: ' Nike',
			rating: 4.55,
			numReviews: 8,
			countInStock: 16,
			description: 'high quality pant',
		},
		{
			_id: '4',
			name: 'Best Pants',
			category: 'Pants',
			image: '/images/p2.jpg',
			price: 5000,
			brand: ' Nike',
			rating: 4.5,
			numReviews: 18,
			countInStock: 6,
			description: 'high quality pant',
		},
		{
			_id: '5',
			name: 'Slim Shirt',
			category: 'Shirts',
			image: '/images/d1.jpg',
			price: 14500,
			brand: ' Nike',
			rating: 4.75,
			numReviews: 10,
			countInStock: 4,
			description: 'high quality shirt',
		},
		{
			_id: '6',
			name: 'Fit Shirt',
			category: 'Shirts',
			image: '/images/d2.jpg',
			price: 9000,
			brand: ' Nike',
			rating: 3.2,
			numReviews: 8,
			countInStock: 0,
			description: 'low quality shirt',
		},
		{
			_id: '7',
			name: 'Best Pants',
			category: 'Pants',
			image: '/images/p1.jpg',
			price: 8000,
			brand: ' Nike',
			rating: 4.5,
			numReviews: 18,
			countInStock: 12,
			description: 'high quality pant',
		},
		{
			_id: '8',
			name: 'Best Pants',
			category: 'Pants',
			image: '/images/p2.jpg',
			price: 5000,
			brand: ' Nike',
			rating: 2.5,
			numReviews: 12,
			countInStock: 0,
			description: 'low quality pant',
		},
	],
}

export default data
