import bcrypt from 'bcryptjs'

const data = {
	users: [
		{
			name: 'JustFidel',
			email: 'admin@justfidel.com',
			password: bcrypt.hashSync('001004'),
			isAdmin: true,
		},
		{
			name: 'Talitha',
			email: 'user@justfidel.com',
			password: bcrypt.hashSync('123456'),
			isAdmin: false,
		},
	],
	products: [
		{
			name: 'Slim Shirt',
			category: 'Shirts',
			image: '/images/d1.jpg',
			price: 6000,
			brand: 'Adidas',
			rating: 4.85,
			numReviews: 10,
			countInStock: 12,
			description: 'high quality shirt',
		},
		{
			name: 'Fit Shirt',
			category: 'Shirts',
			image: '/images/d2.jpg',
			price: 7500,
			brand: 'Nike',
			rating: 4.25,
			numReviews: 5,
			countInStock: 0,
			description: 'high quality shirt',
		},
		{
			name: 'Best Pants',
			category: 'Pants',
			image: '/images/p1.jpg',
			price: 7000,
			brand: 'Puma',
			rating: 4.55,
			numReviews: 8,
			countInStock: 16,
			description: 'high quality pant',
		},
		{
			name: 'Fit Pants',
			category: 'Pants',
			image: '/images/p2.jpg',
			price: 5000,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 18,
			countInStock: 6,
			description: 'high quality pant',
		},
		{
			name: 'Slim Shirt 2',
			category: 'Shirts',
			image: '/images/d1.jpg',
			price: 14500,
			brand: 'Puma',
			rating: 4.75,
			numReviews: 10,
			countInStock: 4,
			description: 'high quality shirt',
		},
		{
			name: 'Fit Shirt 2',
			category: 'Shirts',
			image: '/images/d2.jpg',
			price: 9000,
			brand: 'Adidas',
			rating: 3.2,
			numReviews: 8,
			countInStock: 0,
			description: 'low quality shirt',
		},
		{
			name: 'Best Pants 2',
			category: 'Pants',
			image: '/images/p1.jpg',
			price: 8000,
			brand: ' Nike',
			rating: 4.5,
			numReviews: 18,
			countInStock: 12,
			description: 'high quality pant',
		},
		{
			name: 'Fit Pants 2',
			category: 'Pants',
			image: '/images/p2.jpg',
			price: 5000,
			brand: 'Puma',
			rating: 2.5,
			numReviews: 12,
			countInStock: 0,
			description: 'low quality pant',
		},
		{
			name: 'Slim Shirt 3',
			category: 'Shirts',
			image: '/images/d1.jpg',
			price: 6000,
			brand: 'Adidas',
			rating: 4.85,
			numReviews: 10,
			countInStock: 12,
			description: 'high quality shirt',
		},
		{
			name: 'Fit Shirt 3',
			category: 'Shirts',
			image: '/images/d2.jpg',
			price: 7500,
			brand: 'Nike',
			rating: 4.25,
			numReviews: 5,
			countInStock: 0,
			description: 'high quality shirt',
		},
		{
			name: 'Best Pants 3',
			category: 'Pants',
			image: '/images/p1.jpg',
			price: 7000,
			brand: 'Nike',
			rating: 4.55,
			numReviews: 8,
			countInStock: 16,
			description: 'high quality pant',
		},
		{
			name: 'Fit Pants 3',
			category: 'Pants',
			image: '/images/p2.jpg',
			price: 5000,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 18,
			countInStock: 6,
			description: 'high quality pant',
		},
		{
			name: 'Slim Shirt 4',
			category: 'Shirts',
			image: '/images/d1.jpg',
			price: 14500,
			brand: 'Nike',
			rating: 4.75,
			numReviews: 10,
			countInStock: 4,
			description: 'high quality shirt',
		},
		{
			name: 'Fit Shirt 4',
			category: 'Shirts',
			image: '/images/d2.jpg',
			price: 9000,
			brand: 'Puma',
			rating: 3.2,
			numReviews: 8,
			countInStock: 0,
			description: 'low quality shirt',
		},
		{
			name: 'Best Pants 4 ',
			category: 'Pants',
			image: '/images/p1.jpg',
			price: 8000,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 18,
			countInStock: 12,
			description: 'high quality pant',
		},
		{
			name: 'Fit Pants 4',
			category: 'Pants',
			image: '/images/p2.jpg',
			price: 5000,
			brand: 'Adidas',
			rating: 2.5,
			numReviews: 12,
			countInStock: 0,
			description: 'low quality pant',
		},
	],
}

export default data
